### ISSUE TITLE
Cannot find the model file "cnn_v72.onnx“

### ISSUE THREAD

**Issue by Arles1985** [PLCnext/RockPaperScissors#1]
After running "uvicorn src.main:app" in PyCharm terminal，it displays “ValueError: Model not found "cnn_v72.onnx".” 
Could you please offer me some help? Thanks very much.

**Comment by GPla** [comment]
Hi, as mentioned in the readme, the model is not included in this repository. You can train your own model following the instructions in the models folder.

However, I uploaded the [cnn_v72.onnx](https://drive.google.com/file/d/1N6b6CaRUF6ZvSMxE-QaSqwtQ_eKpLZ_-/view?usp=drive_link) for you to download. Move the file to src/static/model and the error should be resolved.
